name: generate-snake

on:
  schedule:
    - cron: "0 0 * * *"  # roda todo dia à meia-noite
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: seu-usuario-aqui

          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

         
          color_dots: '#161b22,#161b22,#161b22,#161b22,#ffffff'
          color_snake: '#8b5cf6'
          color_empty: '#161b22'
          color_bar: '#26a641'

      - name: Commit e push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Atualizar github-snake.svg"
          git push
